version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.48-22.2
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_URLS: "ldap:/// ldaps:///"
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
 
    keycloak:
    image: dcm4che/keycloak:10.0.1
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
      - "7600:7600"
    environment:
      DB_VENDOR: mysql
      MYSQL_ROOT_PASSWORD: 13972684

      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      KEYCLOAK_DB_CONNECTION_URL: jdbc:mysql://54.203.63.57:3306/keycloak
      JGROUPS_DISCOVERY_EXTERNAL_IP: gunter-nb
      JGROUPS_DISCOVERY_INITIAL_HOSTS: "gunter-nb[7600],test-ng[7600]"
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      LDAP_URL: ldaps://gunter-nb:636
      KEYCLOAK_WAIT_FOR: ldap:636 mariadb:3306
    depends_on:
      - ldap
      - mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
